### ISSUE TITLE
States option

### ISSUE THREAD

**Issue by rotcop4u2** [custom-cards/entity-attributes-card#3]
Hi,

I'm curious if there is a way for the js code to be written to include a ".state" at the end of the sensors. I have tried different ways but realized that the code will not pull states.

thank you

**Comment by bcutter** [comment]
@rotcop4u2 if your intention was to show the state of an entity instead of "only" attributes (well, that´s what this card promises), I´m in and would also like to see this.

Why did you close this issue?
