### ISSUE TITLE
sonos_group attribute

### ISSUE THREAD

**Issue by IanAdd** [custom-cards/entity-attributes-card#7]
For some reason the sonos_group attribute does not wrap and the card line overruns. I'm using a vertical and horizontal stack. Not sure if that is related. 
Perhaps it's because the list has no spaces and hence is seen as one word ?

![overrun](https://user-images.githubusercontent.com/10492213/68730711-b646c480-0621-11ea-8e0d-0d62369ab458.jpg)

**Comment by iantrich** [comment]
right, CSS is hard-wired to break on spaces
